# Generated by Django 5.1.5 on 2025-02-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_remove_userdetails_password_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
