# Generated by Django 5.1.5 on 2025-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_remove_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(),
        ),
    ]
